### ISSUE TITLE
Need a more elegant way to filter out non-3D printers from serial ports 

### ISSUE THREAD

**Issue by Lars-Codes** [sunyhydralab/QView3D#44]
On server/models/printers.py, the getConnectedPorts method is called when the user goes to Registration, clicks "Register Printer," and select device, a list of the connected serial ports appears. 

Right now, in the getConnectedPorts method, we filter out non-3D printer ports with the line: 
`            if (("original" in port.description.lower()) or ("prusa" in port.description.lower())) and (Printer.getPrinterByHwid(hwid_without_location) is None) :
`
We need a more elegant way to filter out non-3D printers that isn't string-matching. We'd like to expand this to more printers than just Prusa, so idk. Good luck hahaha

**Comment by ndg8743** [comment]
fixed with refactor, pull req #80
