### ISSUE TITLE
Figure out when to "start timer"  

### ISSUE THREAD

**Issue by Lars-Codes** [sunyhydralab/QView3D#46]
In server/models/printers.py, in parseGcode, we have this line: 

`                    if("M569" in line) and job.getTimeStarted()==0:
`
We choose this Gcode line to "start" the timer. However, this is a GCode line that is included in GCode files sliced by the Prusa Slicer specifically for MK4. If we want to expand this to more printers, we need a less hardcoded way to "start" the timer. How do we know when the printer starts extruding if this isn't a universal command? 

There may be a JSON file that lists all of the GCode lines that mark first extrude. The exact lines may differ depending on both the type of 3D printer and also the specific slicer you are using. Figure out when to mark the timer start using a more universal method.

**Comment by ndg8743** [comment]
fixed with refactor, pull req #80
