### ISSUE TITLE
Can't submit comments >500 characters 

### ISSUE THREAD

**Issue by Lars-Codes** [sunyhydralab/QView3D#55]
Right now, even though the database specifies VARCHAR(500) for comments, it lets you put as many characters as you want. On the frontend, when the user adds a comment, it should say 1/500, 2/500, etc and disable the submit button if they type > 500 characters. 

If necessary we can make this # larger, but for now keep at 500.

**Comment by iron768** [comment]
added in https://github.com/sunyhydralab/QView3D/pull/75
