### ISSUE TITLE
Git clone from Readme does not work

### ISSUE THREAD

**Issue by shift16** [sunyhydralab/QView3D#72]
The command `git clone https://github.com/sunyhyralab/QView3D.git` does not work  with the error "repository not found"

**Comment by L10nhunter** [comment]
You should probably make sure that you're spelling sunyhydralab correctly. It isn't in this.

**Comment by iron768** [comment]
> You should probably make sure that you're spelling sunyhydralab correctly. It isn't in this.

This is incorrect, he is referring to the main README.md which has a misspelling:

`git clone https://github.com/sunyhyralab/QView3D.git`

The correct one is:

`git clone https://github.com/sunyhydralab/QView3D.git`

**Comment by iron768** [comment]
fixed in https://github.com/sunyhydralab/QView3D/pull/75
